In [27]:
import math
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import tensorflow as tf 

%matplotlib inline

## Testing the package working or not
###  - test tensorflow and pandas 

In [28]:
df = pd.read_excel('BTC daily_database.xlsx', sheet_name=1)
# testing the input is correct or not
print(df[73:89])

         Date  Normalize RSI  Stedev from 20 MA  MACD n.f  dist from 50MA  \
73 2012-04-15       0.651163           1.168733  0.921887       -0.014044   
74 2012-04-16      -0.210526           0.573481  0.973192       -0.006004   
75 2012-04-17       0.151899           1.127236  1.062393       -0.015904   
76 2012-04-18       0.943820           2.406680  1.283761       -0.041836   
77 2012-04-19       0.977778           2.155484  1.479964       -0.044475   
78 2012-04-20       1.481481           2.932215  1.851736       -0.080374   
79 2012-04-21       2.505495           1.928127  2.021115       -0.062510   
80 2012-04-22       1.885057           1.375297  2.081530       -0.049423   
81 2012-04-23       0.349515          -0.135091  1.810204       -0.002863   
82 2012-04-24       0.912281           0.679868  1.742938       -0.029765   
83 2012-04-25       0.740741           0.791767  1.693208       -0.034893   
84 2012-04-26       0.654545           0.557417  1.583709       -0.028588   

In [4]:
w = tf.Variable(0,dtype=tf.float32)
cost = tf.add(tf.add(w**2,tf.multiply(-10.,w)),25)
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(w))

0.0


In [5]:
sess.run(train)
print(sess.run(w))

0.099999994


In [6]:
for i in range(1000):
    sess.run(train)
print(sess.run(w))

4.9999886


## Input dataframe

In [7]:
inputX = df.iloc[75:,2:6 ]
inputX = inputX.T
inputY = None
print("X_train shape: " + str(inputX.shape))
print("number of training samples = "+ str(inputX.shape[1]))
print("number of variables = " + str(inputX.shape[0]))
print(inputX)

X_train shape: (4, 2208)
number of training samples = 2208
number of variables = 4
                        75         76         77         78         79    \
Stedev from 20 MA   1.127236   2.406680   2.155484   2.932215   1.928127   
MACD n.f            1.062393   1.283761   1.479964   1.851736   2.021115   
dist from 50MA     -0.015904  -0.041836  -0.044475  -0.080374  -0.062510   
RSI                51.898734  61.797753  62.222222  68.518519  81.318681   

                        80         81         82         83         84    \
Stedev from 20 MA   1.375297  -0.135091   0.679868   0.791767   0.557417   
MACD n.f            2.081530   1.810204   1.742938   1.693208   1.583709   
dist from 50MA     -0.049423  -0.002863  -0.029765  -0.034893  -0.028588   
RSI                73.563218  54.368932  61.403509  59.259259  58.181818   

                     ...           2273       2274       2275       2276  \
Stedev from 20 MA    ...      -0.799475  -2.254130  -1.936735  -1.309428   
MAC

## layer size 

In [11]:
n_x = inputX.shape[0] # size of input layer
n_h = 5
n_y = 5
print("n_x's shape = " + str(n_x))
print("first layer(n_h)'s shape = " + str(n_h))

n_x's shape = 4
first layer(n_h)'s shape = 5


## Create placeholder


In [68]:
def create_placeholders(n_x, n_y):
    
    #Creates the placeholders for the tensorflow session.
    
    X = tf.placeholder(tf.float32, shape = [n_x,None])
    Y = tf.placeholder(tf.float32, shape = [n_y, None])  
    return X, Y

In [69]:
X, Y = create_placeholders(n_x,n_y)
print ("X = " + str(X))
print ("Y = " + str(Y))

X = Tensor("Placeholder:0", shape=(4, ?), dtype=float32)
Y = Tensor("Placeholder_1:0", shape=(5, ?), dtype=float32)


## Initialize parameters

In [75]:

def initialize_parameters(n_x, n_h):
    #Initializes weight parameters to build a neural network with tensorflow  
    #tf.set_random_seed()                              
    W1 = tf.get_variable("W1", [n_h,n_x], initializer=tf.contrib.layers.xavier_initializer(seed=0))
    b1 = tf.get_variable("b1", [n_h,1], initializer = tf.zeros_initializer())
    W2 = tf.get_variable("W2", [5, n_h], initializer=tf.contrib.layers.xavier_initializer(seed=0))
    b2 = tf.get_variable("b2", [5,1], initializer = tf.zeros_initializer())
    W3 = tf.get_variable("W3", [5, 5], initializer=tf.contrib.layers.xavier_initializer(seed=0))
    b3 = tf.get_variable("b3", [5,1], initializer = tf.zeros_initializer())
    W4 = tf.get_variable("W4", [5, 5], initializer=tf.contrib.layers.xavier_initializer(seed=0))
    b4 = tf.get_variable("b4", [5,1], initializer = tf.zeros_initializer())

    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2,
                  "W3": W3,
                  "b3": b3,
                  "W4": W4,
                  "b4": b4}

    return parameters

In [76]:
tf.reset_default_graph()
with tf.Session() as sess:
    parameters = initialize_parameters(n_x, n_h)
    print("W1 = " + str(parameters["W1"]))
    print("b1 = " + str(parameters["b1"]))
    print("W2 = " + str(parameters["W2"]))
    print("b2 = " + str(parameters["b2"]))
    print("W3 = " + str(parameters["W3"]))
    print("b3 = " + str(parameters["b3"]))
    print("W4 = " + str(parameters["W4"]))
    print("b4 = " + str(parameters["b4"]))

W1 = <tf.Variable 'W1:0' shape=(5, 4) dtype=float32_ref>
b1 = <tf.Variable 'b1:0' shape=(5, 1) dtype=float32_ref>
W2 = <tf.Variable 'W2:0' shape=(5, 5) dtype=float32_ref>
b2 = <tf.Variable 'b2:0' shape=(5, 1) dtype=float32_ref>
W3 = <tf.Variable 'W3:0' shape=(5, 5) dtype=float32_ref>
b3 = <tf.Variable 'b3:0' shape=(5, 1) dtype=float32_ref>


## One hot matrix

In [13]:
def one_hot_matrix(labels, C):
    """
    Creates a matrix where the i-th row corresponds to the ith class number and the jth column
                     corresponds to the jth training example. So if example j had a label i. Then entry (i,j) 
                     will be 1. 
                     
    Arguments:
    labels -- vector containing the labels 
    C -- number of classes, the depth of the one hot dimension
    
    Returns: 
    one_hot -- one hot matrix
    """
    
    ### START CODE HERE ###
    
    # Create a tf.constant equal to C (depth), name it 'C'. (approx. 1 line)
    C = tf.constant(C, name = "C")
    
    # Use tf.one_hot, be careful with the axis (approx. 1 line)
    one_hot_matrix = tf.one_hot(indices = labels, depth = C,axis  =0)
    
    # Create the session (approx. 1 line)
    sess = tf.Session()
    
    # Run the session (approx. 1 line)
    one_hot = sess.run(one_hot_matrix)
    
    # Close the session (approx. 1 line). See method 1 above.
    sess.close()

    
    ### END CODE HERE ###
    
    return one_hot

In [16]:
labels = np.array([1,2,3,0,2,1])
one_hot = one_hot_matrix(labels, C = 4)
print ("one_hot = " + str(one_hot))

one_hot = [[0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]]


## Convert Y-hat to softmax matrix

In [29]:
inputY 
Y = one_hot_matrix(inputY, C = 5)
print("Y = ")
print(Y)

Y = 
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## Forward Propagation

In [ ]:
def forward_propagation(X, parameters):
    """
    Implements the forward propagation for the model: LINEAR -> Sigmoid -> LINEAR -> RELU -> LINEAR -> RELU -> LINEAR -> SOFTMAX
    
    Arguments:
    X -- input dataset placeholder, of shape (input size, number of examples)
    parameters -- python dictionary containing your parameters "W1", "b1", "W2", "b2", "W3", "b3", "W4", "b4"
                  the shapes are given in initialize_parameters

    Returns:
    Z4 -- the output of the last LINEAR unit
    """
    
    # Retrieve the parameters from the dictionary "parameters" 
    W1 = parameters['W1']
    b1 = parameters['b1']
    W2 = parameters['W2']
    b2 = parameters['b2']
    W3 = parameters['W3']
    b3 = parameters['b3']
    W4 = parameters['W4']
    b4 = parameters['b4']
    
                                                                     # Numpy Equivalents:
    Z1 = tf.add(tf.matmul(W1,X) , b1 )                               # Z1 = np.dot(W1, X) + b1
    A1 = tf.nn.sigmoid(Z1)                                           # A1 = sigmoid(Z1)
    Z2 = tf.add(tf.matmul(W2,A1), b2 )                               # Z2 = np.dot(W2, a1) + b2
    A2 = tf.nn.relu(Z2)                                              # A2 = relu(Z2)
    Z3 = tf.add(tf.matmul(W3,A2), b3)                                # Z3 = np.dot(W3,Z2) + b3
    A3 = tf.nn.relu(Z3)                                              # A3 = relu(Z2)
    Z4 = tf.add(tf.matmul(W4,A3), b4)                                # Z4 = np.dot(W3,Z2) + b3 
    
    return Z4

## Compute Cost

In [78]:
def compute_cost(Z4, Y):
    """
    Computes the cost
    
    Arguments:
    Z4 -- output of forward propagation (output of the last LINEAR unit), of shape (6, number of examples)
    Y -- "true" labels vector placeholder, same shape as Z4
    
    Returns:
    cost - Tensor of the cost function
    """
    
    # to fit the tensorflow requirement for tf.nn.softmax_cross_entropy_with_logits(...,...)
    logits = tf.transpose(Z4)
    labels = tf.transpose(Y)
    
    #compute cost
    cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits = logits, labels = labels))
    
    return cost

In [26]:
tf.reset_default_graph()

with tf.Session() as sess:
    X, Y = create_placeholders(12288, 6)
    parameters = initialize_parameters()
    Z4 = forward_propagation(X, parameters)
    cost = compute_cost(Z4, Y)
    print("cost = " + str(cost))

NameError: name 'create_placeholders' is not defined

## Building the model 

In [ ]:
def model(inputX, inputY, learning_rate = 0.0001,
          num_epochs = 1500, minibatch_size = 32, print_cost = True):
    """
    Implements a three-layer tensorflow neural network: LINEAR->RELU->LINEAR->RELU->LINEAR->SOFTMAX.
    
    learning_rate -- learning rate of the optimization
    num_epochs -- number of epochs of the optimization loop
    minibatch_size -- size of a minibatch
    print_cost -- True to print the cost every 100 epochs
    
    Returns:
    parameters -- parameters learnt by the model. They can then be used to predict.
    """
    
    ops.reset_default_graph()                         # to be able to rerun the model without overwriting tf variables
    tf.set_random_seed(1)                             # to keep consistent results
    seed = 3                                          # to keep consistent results
    (n_x, m) = inputX.shape                           # (n_x: input size, m : number of examples in the train set)
    n_y = inputY.shape[0]                             # n_y : output size
    costs = []                                        # To keep track of the cost
    
    # Create Placeholders of shape (n_x, n_y)
    X, Y = create_placeholders(n_x, n_y)

    # Initialize parameters
    parameters = initialize_parameters()

    # Forward propagation: Build the forward propagation in the tensorflow graph
    Z4 = forward_propagation(X, parameters)

    # Cost function: Add cost function to tensorflow graph
    cost = compute_cost(Z4, Y)

    # Backpropagation: Define the tensorflow optimizer. Use an AdamOptimizer.
    optimizer = tf.train.AdamOptimizer(learning_rate = learning_rate).minimize(cost)

    # Initialize all the variables
    init = tf.global_variables_initializer()

    # Start the session to compute the tensorflow graph
    with tf.Session() as sess:

        # Run the initialization
        sess.run(init)

        # Do the training loop
        for epoch in range(num_epochs):

            epoch_cost = 0.                       # Defines a cost related to an epoch
            num_minibatches = int(m / minibatch_size) # number of minibatches of size minibatch_size in the train set
            seed = seed + 1
            minibatches = random_mini_batches(X_train, Y_train, minibatch_size, seed)

            for minibatch in minibatches:

                # Select a minibatch
                (minibatch_X, minibatch_Y) = minibatch

                # IMPORTANT: The line that runs the graph on a minibatch.
                # Run the session to execute the "optimizer" and the "cost", the feedict should contain a minibatch for (X,Y).
                _ , minibatch_cost = sess.run([optimizer, cost], feed_dict={X: minibatch_X, Y: minibatch_Y})

                epoch_cost += minibatch_cost / num_minibatches

            # Print the cost every epoch
            if print_cost == True and epoch % 100 == 0:
                print ("Cost after epoch %i: %f" % (epoch, epoch_cost))
            if print_cost == True and epoch % 5 == 0:
                costs.append(epoch_cost)

        # plot the cost
        plt.plot(np.squeeze(costs))
        plt.ylabel('cost')
        plt.xlabel('iterations (per tens)')
        plt.title("Learning rate =" + str(learning_rate))
        plt.show()

        # lets save the parameters in a variable
        parameters = sess.run(parameters)
        print ("Parameters have been trained!")

        # Calculate the correct predictions
        correct_prediction = tf.equal(tf.argmax(Z4), tf.argmax(Y))

        # Calculate accuracy on the test set
        accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))

        print ("Train Accuracy:", accuracy.eval({X: X_train, Y: Y_train}))
        print ("Test Accuracy:", accuracy.eval({X: X_test, Y: Y_test}))

        return parameters

In [ ]:
# run the model 
parameters = model(X_train, Y_train, X_test, Y_test)